version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_NAME=ImageSearchWebapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  web:
    build: .
    command: bash -c "
            cd ImageSearcher && celery -A ImageSearcher  worker -f celery.logs --detach &&
            python3 manage.py migrate &&  
            python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/ImageSearcher/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ImageSearchWebapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      - db
      - rabbitmq
