version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=ImageSearchWebapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 ImageSearcher/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ImageSearchWebapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      - db